name: pigeon_build_runner
description: Seamlessly integrate pigeon with build_runner for efficient code generation and streamlined development.
homepage: https://github.com/rotorgames/pigeon_build_runner
repository: https://github.com/rotorgames/pigeon_build_runner
issue_tracker: https://github.com/rotorgames/pigeon_build_runner/issues
documentation: https://github.com/rotorgames/pigeon_build_runner/blob/main/README.md
version: 2.0.0
publish_to: none

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  pigeon_build_config:
    git:
      url: https://github.com/skylon07/pigeon_build_runner_infer_inputs.git
      ref: dependable-updated
      path: packages/pigeon_build_config
  pigeon_build_core:
    git:
      url: https://github.com/skylon07/pigeon_build_runner_infer_inputs.git
      ref: dependable-updated
      path: packages/pigeon_build_core
  build: ^2.4.0
  pigeon: ">=24.0.0"
  scratch_space: ^1.0.0
  path: ^1.8.3
  glob: ^2.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
